# Generated by Django 4.2.3 on 2023-08-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_alter_order_registrated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Э', 'Электронно'), ('Н', 'Нальчностью')], db_index=True, max_length=2, null=True, verbose_name='Способ оплаты'),
        ),
    ]
