# Generated by Django 4.2.3 on 2023-08-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_remove_orderitem_restaurant_order_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('З', 'Завершённый'), ('Н', 'Необработанный'), ('Г', 'Готовится')], db_index=True, default='Н', max_length=2, verbose_name='Статус'),
        ),
    ]
